### ISSUE TITLE
driva not build ?

### ISSUE THREAD

**Issue by trebmuh** [openAVproductions/openAV-ArtyFX#21]
I just built 1.3, and:
```
$ lv2ls |grep openav
http://www.openavproductions.com/artyfx#bitta
http://www.openavproductions.com/artyfx#della
http://www.openavproductions.com/artyfx#ducka
http://www.openavproductions.com/artyfx#filta
http://www.openavproductions.com/artyfx#kuiza
http://www.openavproductions.com/artyfx#masha
http://www.openavproductions.com/artyfx#panda
http://www.openavproductions.com/artyfx#roomy
http://www.openavproductions.com/artyfx#satma
http://www.openavproductions.com/artyfx#vihda
http://www.openavproductions.com/artyfx#whaaa
```

would you have any idea why I do not have driva here ?

**Comment by harryhaaren** [comment]
Hey, yes you're right, Driva is still undergoing some testing - it is compiled and installed, but the entry in the manifest.ttl is commented out (so that hosts won't discover it).

To re-enable (no need to compile, will work with packaged versions), open the manifest file probably at (`/usr/lib/lv2/artyfx.lv2/manifest.ttl`) and uncomment the Driva section, (Note the removed # symbols at the start of the line)
```
# Unfinished for this release - NOT ready for testing / usage.
<http://www.openavproductions.com/artyfx#driva> a lv2:Plugin ;
  lv2:binary <artyfx.so> ;
  rdfs:seeAlso <driva.ttl> .
```
Driva will be enabled by default in a future release (hopefully 1.4) after more testing and feedback.
@trebmuh  - if you can make it mis-behave, please file a bug report. And if you can't, please inform me that you feel it is ready for stable release :)

**Comment by trebmuh** [comment]
Thanks Harry. I'll let you know if I'm able to make it misbehave or if I think it's ok for release.
