### ISSUE TITLE
Installs to incorrect directory

### ISSUE THREAD

**Issue by hellocatfood** [openAVproductions/openAV-ArtyFX#34]
I've installed the plugin bundle (Ubuntu 19.04) but it can't be found by programs like Ardour, LMMS etc. Upon further inspection I found that it installed it to /usr/local/lib/lv2 when all of the other plugins are installed at /usr/lib/lv2

**Comment by harryhaaren** [comment]
Hi, this depends very much on your environment configuration (as to where LV2 plugins are searched for), and in general it is rude for a project to install itself system-wide in `/usr/lib`. Locally compiled software should go to `/usr/local/*` unless the user specifies otherwise. With meson this can be achieved using `meson configure -Dprefix=/usr`. I'll close this, as I don't feel it is an issue.

**Comment by hellocatfood** [comment]
Thanks for the explanation, makes sense!
